### ISSUE TITLE
plot scripts

### ISSUE THREAD

**Issue by lu-kas** [FireDynamics/LEDSmokeAnalysis#21]
* have a concept for plotting data across experiments
* have a helper function to find LED id, based on physical position

* plot types:
  * selected experiment (range), array (range), analysis parameter vs. height (z)
  * dito, but vs. x (other non-normal plane vector)
  * dito, but vs. time for selected LED ids
  * scatter plot, parameter value as color/ size, for all arrays

**Comment by O-Sven** [comment]
plots parameter against height and parameter against time are done

**Comment by O-Sven** [comment]
done
